{
 "title": "Antifraud - Service overview",
 "tags": [ "antifraud" ],
 "time": { "from": "now-2m", "to": "now" },
 "panels": [
  {
   "title": "HTTP RPS (/transactions)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(http_server_requests_seconds_count{uri=\"/transactions\",method=\"POST\"}[1m])"
    }
   ]
  },
  {
   "title": "Fraud alerts created (rate)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(antifraud_fraud_alerts_total{}[1m])"
    }
   ]
  },
  {
   "title": "Kafka ingested tx (rate)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(antifraud_kafka_transactions_ingested_total[1m])"
    }
   ]
  },
  {
   "title": "DB saved tx (rate)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(antifraud_transactions_saved_total[1m])"
    }
   ]
  }
 ]
}